### ISSUE TITLE
Error Handling on New User Creation

### ISSUE THREAD

**Issue by gamiller** [HindsightTwentyTwenty/extension#114] opened 2017-01-11 22:13 UTC
Need to handle user giving us bad information on sign up- no data, bad data, etc.
As well, need to insure that the signup does not have an error from the backend when post request is sent.

**Comment by zatannenbaum** [comment] 2017-01-12 15:22
Duplicate of #74. Added your description to that issue and going to close this one

**Closed as completed by zatannenbaum** 2017-01-12 15:22 UTC
